YACA_STATE_VOICE_RANGE = "yacaVoiceRange"
YACA_STATE_LIP_SYNC = "yacaLipSync"
YACA_STATE_MEGAPHONE = "yacaMegaphone"
YACA_STATE_PHONE_SPEAKER = "yacaPhoneSpeaker"
YACA_STATE_GLOBAL_ERROR_LEVEL = "yacaGlobalErrorLevel"
YACA_STATE_RADIO_PROP = "yacaRadioProp"
